apiVersion: v1
kind: Service
metadata:
  name: fed-reserve-int-rate-predictions-service
spec:
  selector:
    app: fed-reserve-int-rate-predictions
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
